const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');

function generateSecret(len = 32) {
  return crypto.randomBytes(Math.ceil(len * 0.75)).toString('base64url').slice(0, len);
}

function serializeEnvValue(v) {
  const s = String(v ?? '');
  if (/[ \t\r\n]/.test(s) || s.includes('#') || s.includes('"')) {
    const escaped = s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    return `"${escaped}"`;
  }
  return s;
}

function createRl() {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: true,
  });

  rl.stdoutMuted = false;
  rl._writeToOutput = function _writeToOutput(stringToWrite) {
    if (rl.stdoutMuted) {
      rl.output.write('*');
    } else {
      rl.output.write(stringToWrite);
    }
  };

  return rl;
}

function ask(rl, prompt, { def = null, required = false, secret = false } = {}) {
  const suffix = def !== null && def !== undefined && String(def).length
    ? ` [default: ${def}]`
    : '';
  const q = `${prompt}${suffix}: `;

  return new Promise((resolve) => {
    const askOnce = () => {
      if (secret) rl.stdoutMuted = true;
      rl.question(q, (answer) => {
        if (secret) {
          rl.stdoutMuted = false;
          rl.output.write('\n');
        }

        const raw = (answer ?? '').trim();
        const v = raw.length ? raw : (def ?? '');
        if (required && !String(v).trim()) {
          rl.output.write('Value is required.\n');
          return askOnce();
        }
        resolve(v);
      });
    };
    askOnce();
  });
}

async function runFirstRunWizard({ envPath, projectRoot }) {
  const rl = createRl();

  try {
    rl.output.write('\n');
    rl.output.write('╔══════════════════════════════════════════════════════════╗\n');
    rl.output.write('║  GGRD Rewards Bot — First-Run Setup                    ║\n');
    rl.output.write('║                                                        ║\n');
    rl.output.write('║  Public values (bot username, mints, channels, etc.)   ║\n');
    rl.output.write('║  are hardcoded in src/config.js.                       ║\n');
    rl.output.write('║  This wizard only asks for SECRETS.                    ║\n');
    rl.output.write('╚══════════════════════════════════════════════════════════╝\n\n');

    // ── Only secrets ──

    rl.output.write('--- Telegram ---\n');
    const BOT_TOKEN = await ask(rl, 'BOT_TOKEN (from @BotFather)', { required: true, secret: true });

    rl.output.write('\n--- MongoDB passwords ---\n');
    rl.output.write('Default setup uses docker-compose with MongoDB on 127.0.0.1.\n');
    rl.output.write('User/host/db/port are hardcoded. You only set passwords here.\n\n');

    let MONGODB_PASS = await ask(rl, 'App user password (leave empty to auto-generate)', { def: '', secret: true });
    if (!MONGODB_PASS) MONGODB_PASS = generateSecret(32);

    let MONGO_ROOT_PASS = await ask(rl, 'Root password (leave empty to auto-generate)', { def: '', secret: true });
    if (!MONGO_ROOT_PASS) MONGO_ROOT_PASS = generateSecret(32);

    rl.output.write('\n--- Solana RPC ---\n');
    rl.output.write('Default: Tatum public endpoint (rate-limited).\n');
    rl.output.write('For production, use Helius/QuickNode/Alchemy.\n\n');

    const SOLANA_RPC_URL = await ask(rl, 'Solana RPC URL (leave empty for default)', {
      def: '',
    });

    // ── Build .env (secrets only, rest uses config.js DEFAULTS) ──

    const lines = [
      '# Auto-generated by first-run setup wizard',
      '# Public values are hardcoded in src/config.js — only secrets here.',
      '',
      '# Telegram',
      `BOT_TOKEN=${serializeEnvValue(BOT_TOKEN)}`,
      '',
      '# MongoDB passwords',
      `MONGODB_PASS=${serializeEnvValue(MONGODB_PASS)}`,
      `MONGO_ROOT_PASS=${serializeEnvValue(MONGO_ROOT_PASS)}`,
      '',
    ];

    if (SOLANA_RPC_URL) {
      lines.push('# Solana RPC (private)');
      lines.push(`SOLANA_RPC_URL=${serializeEnvValue(SOLANA_RPC_URL)}`);
      lines.push('');
    }

    const dir = path.dirname(envPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    fs.writeFileSync(envPath, lines.join('\n'), { encoding: 'utf-8', mode: 0o600 });

    rl.output.write(`\n[OK] Created: ${envPath}\n`);
    rl.output.write('[NEXT] Start MongoDB:  docker compose up -d mongo\n');
    rl.output.write('[NEXT] Start bot:      npm start   (or pm2 start ecosystem.config.js)\n\n');

    return { ok: true };
  } finally {
    rl.close();
  }
}

module.exports = { runFirstRunWizard };
